apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: genai-rag

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret-store.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: genai-rag-platform
